openapi: 3.0.0
info:
  title: Sample API
  version: 1.1.0
paths:
  /users:
    description: Operations related to users
    get:
      summary: Get all users
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/{userId}:
    get:
      summary: Get user by ID
      responses:
        "200":
          description: Successful response
    put:
      summary: Update user
      responses:
        "200":
          description: User updated successfully
    delete:
      summary: Delete user
      responses:
        "204":
          description: User deleted successfully
  /users/{userId}/posts:
    get:
      summary: Get posts for a user
      responses:
        "200":
          description: Successful response
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        username:
          type: string
          minLength: 3
          maxLength: 50
        email:
          type: string
          format: email
        createdAt:
          type: string
          format: date-time
          readOnly: true
      required:
        - username
        - email
